version: '2'
services:
  syntaxnet:
    image: inemo/syntaxnet_rus
    ports:
      - "8111:9999"
    shm_size: 1024m
    command: server 0.0.0.0 9999
  emodetect-backend:
    image: slapoguzov/emodetect
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SYNTAXNET_HOST: syntaxnet
      SYNTAXNET_PORT: 9999
      MYSTEM_PATH: /libs/mystem
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    volumes:
      - ../libs/mystem:/libs/mystem
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "syntaxnet"